import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, "..");
const contractsRoot = resolve(webRoot, "../contracts");
const allowMissingArtifacts = process.argv.includes("--if-artifacts");
const names = [
  "Registry",
  "RegistryTimelock",
  "Executor",
  "FlashLoanHandler",
  "HandlerAaveV3",
  "HandlerSwap",
  "HandlerFunds",
];

async function readJson(path) {
  return JSON.parse(await readFile(path, "utf8"));
}

let deployments;
try {
  deployments = await readJson(join(contractsRoot, "deployments.json"));
} catch {
  deployments = await readJson(join(contractsRoot, "deployments.example.json"));
}

const abis = {};
try {
  for (const name of names) {
    const artifact = await readJson(join(contractsRoot, "out", `${name}.sol`, `${name}.json`));
    abis[name] = artifact.abi;
  }
} catch (error) {
  if (allowMissingArtifacts && error?.code === "ENOENT") {
    console.warn(
      "Foundry artifacts are not present; using the committed generated bindings. " +
        "Run `pnpm setup` before changing contracts.",
    );
    process.exit(0);
  }
  throw error;
}

const source = `// Generated by scripts/codegen.mjs. Do not edit.
export const deployments = ${JSON.stringify(deployments, null, 2)} as const;
export const abis = ${JSON.stringify(abis, null, 2)} as const;
`;
const target = join(webRoot, "src/generated/contracts.ts");
await mkdir(dirname(target), { recursive: true });
await writeFile(target, source);
console.log(`Generated ${target}`);
